import ProjectDescription

let workspace = Workspace(
  name: "Prowl",
  projects: [
    "App",
    "Mirror/iOS",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)
